import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Input from '../comps/Input'
import { useState, useEffect, useId } from "react";
import {nanoid} from "nanoid"
import Form from '../comps/Form'
import ChoicesList from '../comps/ChoicesList ';
import Answer from '../comps/Answer';


export default function Home() {
//adds choice to the list of decisions and is array of decisions
const [decisionInput,setDecisionInput] = useState([])

function createDecision(){
  if (newInput.length > 0){
    const newDecision = {
      id: nanoid(),
      body: newInput
    }
    setDecisionInput( oldDecision => [...oldDecision, newDecision.body])
     setNewInput("")
  }
  }
  //removes choice from the list of decisions
  const [newInput,setNewInput] = useState("")
  console.log(newInput)

  const handleChange = event => {
  setNewInput(event.target.value)
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>Anti-Decision</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form
        handleChange={handleChange}
        createDecision={createDecision}
        newInput={newInput}
        />

      <ChoicesList decisionInput = {decisionInput}/>
      <Answer chosenOne = {decisionInput}/>
    </div>
  )
}
